name: otobox
description: otobox App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  gradient_text: ^1.0.2
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.2.0
  provider: ^3.1.0
  flutter_svg: ^0.14.1
  flutter_country_picker: ^0.1.4
  webview_flutter: ^0.3.14+1
  shared_preferences: ^0.5.3+4
  flutter_spinkit: ^2.1.0
  rflutter_alert: ^1.0.3
  rating_bar: ^0.2.0
  direct_select_flutter: ^1.0.4
  flutter_html: ^0.11.0
  sqflite: ^1.1.7+1
  path: ^1.6.4
  path_provider: ^1.3.0
  dio: ^3.0.3
  cached_network_image: 2.0.0-rc
  firebase_messaging: ^5.1.6
  rounded_letter: ^0.0.6
  image_picker: ^0.6.1+8
  mime: ^0.9.6+3
  http_parser: ^3.1.3
  shimmer: ^1.0.1
  connectivity: ^0.4.5+2
  timeago: ^2.0.21
  intl: ^0.16.0
  firebase_analytics: ^5.0.6
  google_fonts: ^0.3.9
  extended_image: ^0.7.1
  extended_image_library: ^0.2.0
  image_editor: ^0.1.6
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: otobox
      fonts:
        - asset: assets/fonts/otobox.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
